theme: jekyll-theme-minimal
title: Welcome to my Portfolio!
author:
  name             : "Anna Kuokkanen"
  #avatar           : "profile.png"
  bio              : "BSc in Computer Science, University of Helsinki"
